apiVersion: apps/v1
kind: Deployment
metadata:
  name: malls-operator
  labels:
    app: malls-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: malls-operator
  template:
    metadata:
      labels:
        app: malls-operator
    spec:
      containers:
      - name: malls-operator
        image: noca/mall-operator
