apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mall-operator
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - secrets
    - pods
    - pods/exec
    - pods/log
  verbs:
    - event
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - mall.my.domain
  resources:
  - malls
  verbs:
  - "*"
- apiGroups:
  - mall.my.domain
  resources:
    - malls
    - malls/status
    - malls/finalizers
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
